package errorhanding

import "testing"

func TestRecover(t *testing.T) {
	tryRecover()
}
